#!/usr/bin/env python3

"""
    Copyright 2017 Alex Margarit <http://www.alxm.org/>

    ArduboyImage.py is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ArduboyImage.py is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with ArduboyImage.py.  If not, see <http://www.gnu.org/licenses/>.
"""

import sys
from PIL import Image

class Palette:
    def __init__(self, PaletteName):
        image = Image.open(PaletteName)
        width, height = image.size

        if width < 3 or height < 3:
            print('Invalid palette {}'.format(PaletteName))
            sys.exit(1)

        pixels = image.load()
        white = []

        for x in range(0, width):
            r, g, b = pixels[x, 0]

            if r == 255 and g == 255 and b == 255:
                white.append(pixels[x, 1])

        self.white = white
        self.transparent = pixels[0, 0]
        self.limit = pixels[0, 1]

class Sheet:
    def __init__(self, ImageName, Palette):
        image = Image.open(ImageName)

        self.width, self.height = image.size
        self.pixels = image.load()

        self.frameWidth = 0
        self.frameHeight = 0

        for x in range(0, self.width):
            if self.pixels[x, 0] == Palette.limit:
                break

            self.frameWidth += 1

        for y in range(0, self.height):
            if self.pixels[0, y] == Palette.limit:
                break

            self.frameHeight += 1

class Frame:
    def __init__(self, Palette, Sheet, X, Y):
        self.spriteBytes = []
        self.maskBytes = []

        for yStart in range(Y, Y + Sheet.frameHeight, 8):
            for x in range(X, X + Sheet.frameWidth):
                spriteByte = 0
                maskByte = 0

                for y in range(0, min(Y + Sheet.frameHeight - yStart, 8)):
                    pixel = Sheet.pixels[x, yStart + y]

                    if pixel != Palette.transparent:
                        maskByte |= 1 << y

                    if pixel in Palette.white:
                        spriteByte |= 1 << y

                self.spriteBytes.append(spriteByte)
                self.maskBytes.append(maskByte)

def main(PaletteName, ImageName, UniqueName):
    palette = Palette(PaletteName)
    sheet = Sheet(ImageName, palette)

    spriteBytes = [sheet.frameWidth, sheet.frameHeight]
    maskBytes = []

    for x in range(0, sheet.width, sheet.frameWidth + 1):
        frame = Frame(palette, sheet, x, 0)

        spriteBytes += frame.spriteBytes
        maskBytes += frame.maskBytes

    def formatBytes(Bytes):
        formattedBytes = ''

        for index, byte in enumerate(Bytes):
            if index % 16 == 0:
                formattedBytes += '\n    '

            formattedBytes += '0x{:0>2x},'.format(byte)

        return formattedBytes

    contents = """\
// Generated by gfx/ArduboyImage.py

PROGMEM static const uint8_t z_data_gfx_{0}_buffer[] = {{{1}
}};

PROGMEM static const uint8_t z_data_gfx_{0}_mask[] = {{{2}
}};\
""".format(UniqueName, formatBytes(spriteBytes), formatBytes(maskBytes))

    print(contents)

if __name__ == '__main__':
    if len(sys.argv) != 4:
        print('Usage: {} Palette.png Image.png UniqueName'.format(sys.argv[0]))
        sys.exit(1)
    else:
        main(sys.argv[1], sys.argv[2], sys.argv[3])
