A_APP_NAME = defendpluto.pnd.bin
A_DIR_GFX = assets/gfx
#A_DIR_SFX = assets/sfx
A_DIR_SRC = ../DefendPluto
A_PND_DIR = ../bin/pnd
A_PND_NAME = defendpluto.pnd
A_EMBED_MEDIA = true

#
# You can set A2X_PATH to a hard-coded value
# if you do not have a2x/bin in your $PATH
#
A2X_PATH := $(shell a2x_path)
include $(A2X_PATH)/make/project/Makefile.pandora
