// Generated by gfx/ArduboyImage.py

#ifdef ARDUINO

static const uint8_t z_data_gfx_enemy00_frames = 1;

PROGMEM static const uint8_t z_data_gfx_enemy00_buffer[] = {
    // Frame dimension
    0x07,0x08,

    // Image frames
    0x10,0x38,0x7c,0x08,0x7c,0x38,0x10,

    // Mask frames
    0x10,0x38,0x7c,0x08,0x7c,0x38,0x10,
};

#endif
