// Generated by gfx/ArduboyImage.py

#ifdef ARDUINO

static const uint8_t z_data_gfx_enemy01_frames = 1;

PROGMEM static const uint8_t z_data_gfx_enemy01_buffer[] = {
    0x07,0x08,0x1c,0x38,0x70,0x00,0x70,0x38,0x1c,
};

PROGMEM static const uint8_t z_data_gfx_enemy01_mask[] = {
    0x1c,0x38,0x70,0x00,0x70,0x38,0x1c,
};

#endif
