// Generated by gfx/ArduboyImage.py

#ifdef ARDUINO

static const uint8_t z_data_gfx_enemy02_frames = 1;

PROGMEM static const uint8_t z_data_gfx_enemy02_buffer[] = {
    0x07,0x08,0x3c,0x0f,0x07,0x1e,0x07,0x0f,0x3c,
};

PROGMEM static const uint8_t z_data_gfx_enemy02_mask[] = {
    0x3c,0x0f,0x07,0x1e,0x07,0x0f,0x3c,
};

#endif
