// Generated by gfx/ArduboyImage.py

#ifdef ARDUINO

static const uint8_t z_data_gfx_shield_frames = 1;

PROGMEM static const uint8_t z_data_gfx_shield_buffer[] = {
    0x05,0x08,0x1f,0x3f,0x7f,0x21,0x1f,
};

PROGMEM static const uint8_t z_data_gfx_shield_mask[] = {
    0x1f,0x3f,0x7f,0x3f,0x1f,
};

#endif
