/*
    Copyright 2018 Alex Margarit <alex@alxm.org>
    This file is part of Defend Pluto.
    Generated by gfx/ArduboyImage.py from ../gfx/creds.png
*/

#if Z_PLATFORM_ARDUBOY

static const uint8_t z_data_gfx_creds_frames = 1;

PROGMEM static const uint8_t z_data_gfx_creds_buffer[] = {
    // Frame dimension
    4, 5,

    // Image frames
    0x0e,0x11,0x15,0x04,

    // Mask frames
    0x0e,0x11,0x15,0x04,
};

#elif Z_PLATFORM_GAMEBUINOMETA

static const uint8_t z_data_gfx_creds_frames = 1;

static const uint16_t z_data_gfx_creds_buffer[] = {
    // Frame dimension
    4, 5,

    // Number of frames, looping
    1, 0,

    // Transparent color, color mode
    0xf81f, 0,

    // Image frames
    0xf81f,0xb68d,0xb68d,0xf81f,0xb68d,0xf81f,0xf81f,0xf81f,0xb68d,0xf81f,
    0xb68d,0xb68d,0xb68d,0xf81f,0xf81f,0xf81f,0xf81f,0xb68d,0xb68d,0xf81f,
};

#endif
