// Generated by gfx/ArduboyImage.py

#ifdef ARDUINO

PROGMEM static const uint8_t z_data_gfx_shield_buffer[] = {
    0x05,0x08,0x0f,0x1f,0x3f,0x11,0x0f,
};

PROGMEM static const uint8_t z_data_gfx_shield_mask[] = {
    0x0f,0x1f,0x3f,0x1f,0x0f,
};

#endif
