// Generated by gfx/ArduboyImage.py

#if Z_PLATFORM_ARDUBOY

static const uint8_t z_data_gfx_enemy02_frames = 1;

PROGMEM static const uint8_t z_data_gfx_enemy02_buffer[] = {
    // Frame dimension
    0x07,0x08,

    // Image frames
    0x78,0x1e,0x0e,0x3c,0x0e,0x1e,0x78,

    // Mask frames
    0x78,0x1e,0x0e,0x3c,0x0e,0x1e,0x78,
};

#endif // Z_PLATFORM_ARDUBOY
